### ISSUE TITLE
Erreur au lancement l'application (npm start)

### ISSUE THREAD

**Issue by lhadjadj** [france-connect/identity-providers-examples#2]
Bonjour, 

l'installation a été réalisée sans problème. Lors de l’exécution de la commande npm start, le message d'erreur ci-dessous apparaît : 

"##############################################################"
"#"
"#   !!! MONGOOSE WARNING !!!"
"#"
"#   This is an UNSTABLE release of Mongoose."
"#   Unstable releases are available for preview/testing only."
"#   DO NOT run this in production."
"#"
"##############################################################"

connect-mongo deprecated mongoose_connection option is deprecated. Use mongooseConnection instead app.js:31:12
express-session deprecated undefined resave option; provide resave option app.js:29:9
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option app.js:29:9

/opt/DATA/OPENID-PROV/identity-providers-examples/OpenID-Connect-NodeJS/node_modules/modelling/node_modules/waterline/node_modules/wane-schema/lib/waterline-schema/utils.js:47
  return hop.call(obj, prop);
             ^
TypeError: Cannot convert null to object
    at hasOwnProperty (native)

..........
.......
...
.
npm ERR! authenticationProvider1@0.0.0 start: `./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the authenticationProvider1@0.0.0 start script.
npm ERR! This is most likely a problem with the authenticationProvider1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls authenticationProvider1
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! cwd /opt/DATA/OPENID-PROV/identity-providers-examples/OpenID-Connect-NodeJS
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/DATA/OPENID-PROV/identity-providers-examples/OpenID-Connect-NodeJS/npm-debug.log
npm ERR! not ok code 0

Merci d'avance pour votre aide.

**Comment by fpetitit** [comment]
OK, je reproduis le problème.
Sans doute une petite erreur dans le code qui ne posait pas problème avec les anciennes versions de la librairie Waterline et qui pose problème maintenant.
On revient vers vous dès que c'est corrigé.

**Comment by fpetitit** [comment]
Le problème est résolu.
Par-contre il vous faut faire la manipulation suivante : 
- mettre à jour le code (git pull)
- supprimer le répertoire "node_modules" situé à la racine de l'application OpenID-Connect-NodeJS
- relancer la commande "npm install"

A ce moment, "npm start" devrait fonctionner.

**Comment by lhadjadj** [comment]
Merci cela fonctionne, je vais fermé le ticket. Par contre j'ai d'autres questions sur l'utilisation de l'application, puis-je vous les transmettre par courriel ou depuis GitHub?



**********************************************************************
Laurent HADJADJ (ASP/DIREPS/DP-CM)
Agence de Services et de Paiement,
Direction des Interventions Régionales, de l'Emploi et des Politiques Sociales
Direction de Programme
Chargé de Mission
12, rue Henri ROL-TANGUY   TSA 10001
93555 MONTREUIL SOUS BOIS CEDEX
Tél: 01 73 02 18 76  / Fax. : 01 73 30 26 23   
**********************************************************************
>>> 
De : François Petitit<notifications@github.com>
À :france-connect/identity-providers-examples <identity-providers-examples@noreply.github.com>
CC :Laurent Hadjadj <laurent.hadjadj@asp-public.fr>
Date : 21/05/2015 17:52
Objet : Re: [identity-providers-examples] Erreur au lancement l'application (npm start) (#2)

Le problème est résolu.
Par-contre il vous faut faire la manipulation suivante : 
mettre à jour le code (git pull) 
supprimer le répertoire "node_modules" situé à la racine de l'application OpenID-Connect-NodeJS 
relancer la commande "npm install" 
A ce moment, "npm start" devrait fonctionner.
-
Reply to this email directly or view it on GitHub.
***************** MESSAGE IMPORTANT *******************
*** La pièce jointe à ce courriel a été analysée ***
*** par un antivirus qui n'a rien détecté d'anormal. ***
*** Ceci étant, n'ouvrez pas de pièces jointes quand ***
*** vous ne connaissez pas l'expéditeur du courriel. ***

-------------------------------------------------------------------------------------------------------
Ce message peut contenir des INFORMATIONS CONFIDENTIELLES destinees a l'usage exclusif du destinataire. Si vous le recevez par erreur, merci de bien vouloir nous en avertir immediatement par telephone ou messagerie, de le detruire et de n'en divulguer le contenu a personne.

This message may contain CONFIDENTIAL INFORMATION intended only for use by the addressee. If you have received it by mistake, thank you for notifying us immediately by telephone or by e-mail, and please, delete it and do not deliver it to anyone else .
-------------------------------------------------------------------------------------------------------

**Comment by fpetitit** [comment]
Vous pouvez nous contacter à l'adresse support@dev-franceconnect.fr.

**Comment by lhadjadj** [comment]
Merci pour votre réponse, Le problème a été corrigé.

**Comment by BOREM3110** [comment]
l'installation de l'application marche bien,mais lors del'execution de la commande "npm start la message ci dessous s'affiche:


borem@DESKTOP-7KAUT2F MINGW64 ~/Desktop/a2website
$ npm install
npm WARN deprecated typings@1.5.0: Typings is deprecated in favor of NPM @types
-- see README for more information
npm WARN deprecated @angular/http@2.0.0: Package no longer supported. Use @angul
ar/common instead, see https://angular.io/guide/deprecations#angularhttp
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
npm WARN deprecated popsicle-proxy-agent@3.0.0: Use `agent` option with `popsicl
e` directly

> core-js@2.6.11 postinstall C:\Users\borem\Desktop\a2website\node_modules\core-
js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfill
ing JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Colle
ctive or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a goo
d job -)


> a2website@1.0.0 postinstall C:\Users\borem\Desktop\a2website
> typings install

typings WARN deprecated 2016-10-25: "registry:dt/jasmine#2.2.0+20160621224255" i
s deprecated (updated, replaced or removed)
typings WARN deprecated 2016-11-21: "registry:dt/node#6.0.0+20160909174046" is d
eprecated (updated, replaced or removed)
typings WARN deprecated 2016-9-14: "registry:dt/core-js#0.0.0+20160725163759" is
 deprecated (updated, replaced or removed)

+-- core-js (global)
+-- jasmine (global)
`-- node (global)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"}
 (current: {"node":"12.18.3","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1
npm WARN a2website@1.0.0 No description
npm WARN a2website@1.0.0 No repository field.

added 425 packages from 294 contributors and audited 426 packages in 159.625s

7 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (5 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

borem@DESKTOP-7KAUT2F MINGW64 ~/Desktop/a2website
$ npm install

> a2website@1.0.0 postinstall C:\Users\borem\Desktop\a2website
> typings install

typings WARN deprecated 2016-11-21: "registry:dt/node#6.0.0+20160909174046" is d
eprecated (updated, replaced or removed)
typings WARN deprecated 2016-10-25: "registry:dt/jasmine#2.2.0+20160621224255" i
s deprecated (updated, replaced or removed)
typings WARN deprecated 2016-9-14: "registry:dt/core-js#0.0.0+20160725163759" is
 deprecated (updated, replaced or removed)

+-- core-js (global)
+-- jasmine (global)
`-- node (global)

npm WARN a2website@1.0.0 No description
npm WARN a2website@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

audited 426 packages in 18.925s

7 packages are looking for funding
  run `npm fund` for details

found 10 vulnerabilities (5 low, 5 high)
  run `npm audit fix` to fix them, or `npm audit` for details

borem@DESKTOP-7KAUT2F MINGW64 ~/Desktop/a2website
$ npm install

> a2website@1.0.0 postinstall C:\Users\borem\Desktop\a2website
> typings install

typings WARN deprecated 2016-11-21: "registry:dt/node#6.0.0+20160909174046" is d
eprecated (updated, replaced or removed)
typings WARN deprecated 2016-10-25: "registry:dt/jasmine#2.2.0+20160621224255" i
s deprecated (updated, replaced or removed)
typings WARN deprecated 2016-9-14: "registry:dt/core-js#0.0.0+20160725163759" is
 deprecated (updated, replaced or removed)

node_modules/rxjs/Subject.d.ts:24:5 - error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.

24     lift<T, R>(operator: Operator<T, R>): Observable<T>;
       ~~~~
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
node_modules/typescript/lib/lib.d.ts:105:14 - error TS2300: Duplicate identifier 'PropertyKey'.

105 declare type PropertyKey = string | number | symbol;
                 ~~~~~~~~~~~


typings/globals/core-js/index.d.ts:3:14 - error TS2300: Duplicate identifier 'PropertyKey'.

3 declare type PropertyKey = string | number | symbol;
               ~~~~~~~~~~~

borem@DESKTOP-7KAUT2F MINGW64 ~/Desktop/a2website
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! a2website@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the a2website@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\borem\AppData\Roaming\npm-cache\_logs\2020-10-22T14_12_02_744Z-debug.log

borem@DESKTOP-7KAUT2F MINGW64 ~/Desktop/a2website
$
